### PR TITLE
Start django project issue4 (really issue #11)

### LINKED ISSUE #11: Set up Initial Master Server Django App
Stand up the basic skeleton for building the new MS functionality within the Python/Django framework.

Originally this was going to get done as part of #4, but I wanted a separate issue that could be completed in short order.

This is a continuation of **Setup Initial Master Server Django App** brata-hsdc/brata#90.

### PR DESCRIPTION
**Pull request by ellerychan**
Resolves #11 

I spawned issue #11 out of issue #4 so I could deliver this initial bit of code.

This pull request delivers a new Eclipse project, a new Django project, 4 new Django apps, a database schema diagram, and a database setup instructions document.

The old PHP Eclipse project was called `m`.  I created a new one called `ms`.  `m` should probably be deleted, but I am using it for reference, so it is still in the baseline.

This delivers a Django project called `ms`, which contains 4 Django apps.  The **dbkeeper** app and the **piservice** app define models for the database.  The **teamcentral** and **scoreboard** apps have no functionality yet.  The models initialize the database successfully, and the Django Admin interface runs.

Here is what it looks like:

django_admin_interface

I added a document called `transition/msdb_database_initialization.md`.  After the merge, I will make a link to it from the wiki.

Things to do next:
- Add some utility scripts to reset the database and fill it with test data.
- Decide about non-admin users: do we want them to log in?
  - If so, we need to think about account creation.  Django does most of it for us.

### CODE REVIEW

**Comment by ellerychan** [comment]
@jawaad-ahmad , @DragonmasterJ , @jaron42 should look at this and approve.

**Comment by ellerychan** [comment]
Yoohoo @jawaad-ahmad

**Comment by DragonmasterJ** [comment]
I can't see anything I disagree with. I'm good for pulling it in.

**Comment by ellerychan** [comment]
@jawaad-ahmad I'm still getting used to navigating things on GitHub.  You commented on some earlier revisions of some of the files.  For example, 

> do we want to continue with SQLite

was from the `settings.py` file in the first commit (d85d30e).  It was later updated to use PostgreSQL.  It's not obvious to me yet how to see the most recent versions of things here in the Pull Request view.  I guess you can click on the **Files** tab at the top of the Pull Request view to see the files that have been changed, but by default it shows all the changes expanded out, so it is not convenient to navigate.

**Comment by ellerychan** [comment]
The code is still heavily in development.  I mostly wanted to push something to go through the process.  I recommend pushing this as-is, and incorporating the feedback in a future Pull Request (probably for Issue #13).

I think we are probably having too much discussion here for a Pull Request.  It seems like it would be less overwhelming if the issues could be handled more incrementally, which would mean more Pull Requests for smaller changes.

I'm just trying to find the happy medium, to code efficiently without too much overhead.

I can just merge this branch, and fix things in a future push (#13), or I can make the changes to this branch before merging it, and merge those changes into my Issue #13 branch, but that will be more work.  What do you suggest?

**Comment by jawaad-ahmad** [comment]
[Interesting post](http://beust.com/weblog/2010/09/15/a-quick-guide-to-pull-requests/) about handling pull requests.

**Comment by jawaad-ahmad** [comment]
> You commented on some earlier revisions of some of the files.

Yes, I assumed so, and later confirmed as I got to the later commits. Being a Git novice and a GitHub newbie, I don't know what to recommend other than I remember reading something about "squashing commits" a while back. Maybe this is what we're supposed to use it for?

> I can just merge this branch, and fix things in a future push (#13), or I can make the changes to this branch before merging it, and merge those changes into my Issue #13 branch, but that will be more work. What do you suggest?

I think since we're all new to GitHub, we can take these opportunities to play around and learn the interface. I tried a couple things during this pull request just to see what happens.

I think this is a good opportunity for us to learn how to "converse" in the pull requests and see how we like it, and also a good opportunity to play with the merging and see what happens.
- Can you come back in and make more comments to this pull request after merging, or does this get closed out?
- Can you pull once, find problems, and then come back here and continue having a conversation, and then pull again?

My understanding is your branch is tied to this pull request now, so any future commits you push from that branch will continue updating this pull request automatically until you delete the branch, which appears to leave the door open for additional fixes until someone is sure that we want to close out the branch by deleting it.

Also FYI: My standard disclaimer applies to my review comments:
- You're the author of the code, so you know best.
- As the author, you have final say on whether or not to accept my comment or dismiss it.
- Take most of my comments as suggestions or rants while I was browsing the changes with the goal of provoking thought and discussion.
- If I feel strongly about any particular comment, my choice of wording in the comment should already indicate this so buyer beware if you choose to ignore it (unless it's something that impacts me now or later, in which case you'll be hearing from me again once I get around to noticing it).

**Comment by ellerychan** [comment]
I agree that we are still finding the optimal way to interact in this environment.

I like that you can insert comments near the relevant lines of code in one of the Pull Request views.

I have a hard time with a barrage of requests because I want to read them all before I start dealing with them, but then I lose track of where they are because after I read one it drops off of my Notifications list.

It is hard for me to keep a mental picture of where everything is, between the different files in the different commits in the Pull Request, the Issue threads, the wiki, and the actual code branches.  So sometimes when I want to go back to comment on something I can't even find it before I forget what I wanted to say or get distracted by another issue.

**Comment by jawaad-ahmad** [comment]
> I have a hard time with a barrage of requests because I want to read them all before I start dealing with them, but then I lose track of where they are because after I read one it drops off of my Notifications list.

I notice I'm getting e-mails, so I can find what the e-mail refers to, catch up, and then delete the e-mail.

> It is hard for me to keep a mental picture of where everything is, between the different files in the different commits in the Pull Request, the Issue threads, the wiki, and the actual code branches. So sometimes when I want to go back to comment on something I can't even find it before I forget what I wanted to say or get distracted by another issue.

We haven't even gotten to the Gists yet or @DragonmasterJ forum hosting!

How is the search feature on this site? I've been able to put in a couple words and find what I was looking for so far.

**Comment by ellerychan** [comment]
I've been deleting the emails and just trying to go through the Notification list on the website.

**Comment by DragonmasterJ** [comment]
As far as forums, we may want to discuss that a bit internally. I know Ellery was up for keeping as much on this site as possible, so I've been leaving it up to issues and pull request so far until we see a need for something else external. 
If we agree with this for the Master Server, do we want all the teams to follow suit to stay consistent? I can still do some research on comms, especially within GitHub, I've just been distracted with trying to learn the new MS code. And if we want to at least research and document outside options, I can jump on the research again this weekend. 
@ellerychan @jawaad-ahmad Opinions?

**Comment by jawaad-ahmad** [comment]
@DragonmasterJ I don't think that's necessary; I agree with @ellerychan for now. Let's stick to what we get with GitHub before going out to another service and signing up for additional accounts. I'm still waiting for all the devs to give me their GitHub user names to add here.

If you haven't seen Django code before, it's quite a bit to take in all at once, but if you think about it, it's not too far off from the C# code we see daily. We can sit down and go over it at some point if you feel that will help.

**Comment by ellerychan** [comment]
I say we learn to live within our GitHub bounds.  I think having another conversation stream will just dilute the discourse, plus it will be less convenient to link to things on GitHub.

I also would be happy to help with the Django.  I need to push a little more code out so you can see Django actually doing something.  This Pull Request is taking up too much time.

**Comment by ellerychan** [comment]
I just pushed updates based on the Pull Request feedback.  Waiting for a thumbs-up from @jawaad-ahmad and @DragonmasterJ to merge.

**Comment by jawaad-ahmad** [comment]
I see the changes. Interesting: All the commits aren't at the top; they're at the appropriate point in the conversation. That's nice because I can follow along when it happened, but I can't see at a glance all the commits that are part of this request. It's not so bad; I can search for "added", "commits", or "ago" on this page to find them.

Have you tried merging the pull request yet? I'm curious to know what happens after you merge early for integration, and then we get around to looking at the pull request later and make comments on it. If this is allowed, then we can allow the **hsdc2016** branch to break during integration.

@ellerychan Did you have to do anything more than `push` from your repo to get these to show up, or did GitHub pick up the changes automatically?

Another interesting thing to note is it looks like I'm watching this request, perhaps because I made comments or perhaps because I was `@mentioned`. Still, I believe I got no e-mail from the push; I only got e-mails for the two posts following the push.

Perhaps we should make it part of the process to post a comment on the request with `@mentions` for interested individuals/groups. Maybe don't bother with individuals and only `@mention` groups so everyone in the group gets the notification?

> This Pull Request is taking up too much time.

I would expect that from the first couple pull requests. These are the most important for everyone to look at and provide feedback on, poke at things, ask questions, etc. What we discuss and agree to here will set the tone for the remainder of development.

It's best to hash things out early so we don't repeatedly make comments on the same things over and over.

Plus we're just learning how to use GitHub, so that's also expected during the time for these initial reviews. Overall I'm quite pleased with this compared to Google Code. I imagine they planned for the migration a long time ago considering the work done on the migration and integration of tools, and only announced pulling the plug recently.

Another observation: When reviewing a changed file, I see diffs. I can click in the margin to expand the collapsed section without having to go anywhere else!

**Comment by ellerychan** [comment]
We should have another face-to-face so you can show me all the good GitHub tricks you are learning.  I still feel like I am blundering around following your trail of notifications.

**Comment by ellerychan** [comment]
> Did you have to do anything more than push from your repo to get these to show up, or did GitHub pick up the changes automatically?

I just did a push from my local repo to the branch on the GitHub repo.

**Comment by jawaad-ahmad** [comment]
So you closed the Pull Request but I still see a button to **Delete branch** meaning you didn't delete the branch yet, possibly because you're integrating and might have more changes, or maybe your process requires it to go through QA before the branch gets deleted.

Let's see what happens if I make a comment on a closed Pull Request: How could you merge such buggy code? This code is so horrible it shouldn't see the light of day! Did you learn to code on an abacus, or did it not exist yet?!!

So will this re-open a closed Pull Request?

Before submitting this, let's see what happens if I comment on the now-closed Issue #11. I reopened Issue #11, but it looks like the PR is still closed for now.

I don't see any button to **Reopen**, only **Comment**.

**Comment by jawaad-ahmad** [comment]
Nope. Still closed. I also went to the list of pull requests, found this under the Closed ones, and tried to **Mark As** Open. Still nothing, I guess a closed Pull Request stays closed unless...

Next thing to try would be to push another change to the branch. Care to do so, @ellerychan?

**Pull request merged**
