### PR TITLE
Database cleanup and rebaseline migrations

### PR DESCRIPTION
**Pull request by jaron42**
@ellerychan and @jawaad-ahmad here were the changes from today.

### CODE REVIEW

**Comment by ellerychan** [comment]
@jaron42 Can you share your **db_backup.sql** with me and @jawaad-ahmad ?  I don't think I want to reset my database without some content to initialize it with.  I think that means I can't pull from `hsdc2016` until I can get that from you.

**Comment by ellerychan** [comment]
@jaron42 I see you added the **db_backup.sql** to the repository.

I pulled the latest `hsdc2016` down, dropped my database, created a new one, restored it from **db_backup.sql**, and it all ran without errors.  However, when I try to access the Team table through the Admin interface, or do other things, I now get a _ProgrammingError_ exception thrown with the following error message:

```
column dbkeeper_team.registered_id does not exist
LINE 1: ...er_team"."pass_code", "dbkeeper_team"."reg_code", "dbkeeper_...
```

Is it possible the **db_backup.sql** does not match the current database schema?  Or have I messed up something else?  Any suggestions?

**Comment by jaron42** [comment]
@ellerychan I thought I had fixed that in my last merge as I hit that issue as well on Saturday.  I will verify I have not missed committing it or merging it to hsdc2016.

**Comment by ellerychan** [comment]
@jaron42 I couldn't figure out where the _registered_id_ was coming from.  I searched the Django code for any more uses of that field as a foreign key.  Possibly it is in the **.sql** file, now that I think about it.  It may be related to the following:

While you are looking at that, you should probably look at the flags you are using for `pg_dump`.  I think the **db_backup.sql** you created contains all the commands to rebuild the tables from an empty database.  That is probably not good if we are depending on the Django _migrations_ to set up the tables.  For our development purposes we probably want to just save enough to restore the data.  For actual database snapshots, we probably do want to have it rebuild everything.

**Comment by jaron42** [comment]
@ellerychan I will re-snapshot with just the data, but I have scanned everything on my branch and hsdc2016 and I don't find registered_id anywhere. I was able to find it in the DB backup I did just before we tried to rebuild it from scratch and it is one that removed as a foreign key on the team model, which is why now it doesn't exist anymore.  If you are still seeing it, you must have some residual migration or DB.  When you restarted did you drop the entire database? Also when you pulled latest did git remove your migrations that are out of date now?  Those are the only things I can think that would have still had it left over.

**Comment by ellerychan** [comment]
@jaron42 Hmmm.  If we are meeting tomorrow (Wed.) maybe you can help me fix it.

Yes, migrations are gone.  Only the _0001_initial.py_\* is left.  Yes, I did completely drop the DB.

I fear I'm losing my mojo.  I can't clone my MS SD card either.

**Comment by jaron42** [comment]
@ellerychan see you later today then and we'll get you setup.

**Comment by ellerychan** [comment]
Weird!  Database had a miraculous healing.  Works now.  Maybe the full reboot (when I took the card out to clone it) cleared something out in Postgresql or Apache.

**Pull request merged**
